name: Taskord CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']

    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}

    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: "taskord"
        mysql user: "taskord"
        mysql password: "taskord"

    - name: ğŸ›’ Checkout
      uses: actions/checkout@v2

    - name: ğŸ˜ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        tools: composer:v2, php-cs-fixer, phpunit

    - name: ğŸ—ƒ Copy .env
      run: |
        php -v
        php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: âœ… Validate composer.json and composer.lock
      run: composer validate

    - name: ğŸ“š Cache Composer packages
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: ğŸ¹ Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: ğŸ“š Cache NPM packages
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: ğŸ“¦ Install NPM Dependencies
      run: npm install

    - name: ğŸ— Build CSS and JS
      run: npm run dev

    - name: ğŸ”‘ Generate key
      run: php artisan key:generate

    - name: ğŸ”­ Install Horizon
      run: |
        php artisan horizon:install
        php artisan horizon:publish

    - name: ğŸš Migrate Database
      run: php artisan migrate:refresh --seed

    - name: ğŸƒ Run the Application
      run: php artisan serve & sleep 5 ; kill $! || echo $?

    - name: ğŸ–¥ Test commands
      run: |
        php artisan migrate:fresh --seed
        php artisan user:streaks
        php artisan user:streaks all
        php artisan user:reset-goal

    - name: ğŸ•¸ Validate GraphQL schema
      run: php artisan lighthouse:validate-schema

    - name: ğŸ§ª Execute tests (Unit and Feature tests)
      run: php artisan test
