name: Sail

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Sail
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ›’ Checkout
      uses: actions/checkout@v2

    - name: ğŸ˜ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2

    - name: âœ… Validate composer.json and composer.lock
      run: composer validate

    - name: ğŸ¹ Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: â›µ Start sail
      run: ./vendor/bin/sail up -d
